[package]
name = "gh-velocity"
version = "0.1.0"
authors = ["Nick Cameron <nrc@ncameron.org>"]
edition = "2018"

[dependencies]
futures-preview = { version = "0.3.0-alpha.16", features = ["compat"] }
hubcaps = "0.5"
rusqlite = "0.18"
serde = "1.0"
serde_derive = "1.0"
